name: evente
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  url_launcher: ^6.0.17
  hive: ^2.2.3
  image_picker:
  skeleton_text: ^3.0.0
  hive_flutter: ^1.1.0
  intl: 
  google_maps_flutter: ^2.2.1
  shared_preferences: 
  provider: ^6.0.3
  the_apple_sign_in: ^1.1.1
  google_sign_in: ^6.1.3
  cloud_firestore: ^3.1.6
  get: 
  firebase_core: ^1.11.0
  http:
  firebase_core_platform_interface: 4.5.1
  firebase_messaging: ^11.2.5


  win32: ^5.5.3
  cupertino_icons: ^1.0.2
  package_info: ^2.0.2
  visibility_detector: ^0.4.0+2
  flutter_barcode_listener: ^0.1.3
  # fast_barcode_scanner: ^1.1.0
  # flutter_screenutil: 
  googleapis_auth:
  permission_handler: ^10.2.0
  qr_code_scanner: ^1.0.1
  flutter_svg: 
  map_launcher: ^2.4.0
  geolocator: ^9.0.2
  dotted_border: 
  flutter_local_notifications: ^17.2.2
  
  convex_bottom_bar: ^3.2.0
  readmore: 
  firebase_analytics:
  charts_flutter:
  syncfusion_flutter_charts:
  firebase_auth:
  cached_network_image: ^3.2.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
